# Generated by Django 2.1.1 on 2018-10-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_add_custom_user_model_and_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRO01', 'Camera1'), ('PRO02', 'Camera2')], max_length=2)),
            ],
        ),
    ]
