# Generated by Django 2.1.1 on 2018-10-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_add_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_proton_el001', models.BooleanField(default=False)),
                ('configuration', models.BooleanField(default=False)),
                ('monitoring', models.BooleanField(default=False)),
                ('reporting', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'administration_company_access',
            },
        ),
    ]
