# Generated by Django 2.1.1 on 2018-10-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_add_company_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.CompanyAccess'),
        ),
        migrations.AddField(
            model_name='company',
            name='device_types',
            field=models.ManyToManyField(to='administration.DeviceType'),
        ),
    ]
