# Generated by Django 2.1.2 on 2018-10-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_add_company_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='serial_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
