# Generated by Django 2.1.2 on 2018-10-17 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_add_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaccess',
            name='sms_enabled',
        ),
        migrations.AddField(
            model_name='companyaccess',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Product'),
        ),
    ]
