# Generated by Django 2.1.2 on 2018-10-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_company_access_definition_change_name_of_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='device_types',
        ),
        migrations.RemoveField(
            model_name='device',
            name='connection_status',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='device',
            name='tolerated_offline',
        ),
        migrations.AddField(
            model_name='company',
            name='device',
            field=models.ManyToManyField(to='administration.Device'),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
    ]
