# Generated by Django 2.1.2 on 2018-10-17 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_refactor_device_and_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='device',
        ),
        migrations.AddField(
            model_name='company',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Device'),
        ),
    ]
