# Generated by Django 2.1.2 on 2018-10-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_company_device_FK'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaccess',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='companyaccess',
            name='monitoring',
        ),
        migrations.RemoveField(
            model_name='companyaccess',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='companyaccess',
            name='reporting',
        ),
    ]
