# Generated by Django 2.1.2 on 2018-10-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_refactor_company_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
