# Generated by Django 2.1.2 on 2018-10-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_add_active_field_on_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
