# Generated by Django 2.1.2 on 2018-10-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_device_&_product_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.CompanyAccess'),
        ),
        migrations.AlterField(
            model_name='device',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administration.Company'),
        ),
    ]
