# Generated by Django 2.1.2 on 2018-10-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_company_&_product_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'engineer'), (3, 'supervisor'), (4, 'operator')], default=4),
        ),
    ]
