# Generated by Django 2.1.2 on 2018-10-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0024_remove_old_initial_user_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'admin'), (1, 'engineer'), (2, 'supervisor'), (3, 'operator')], default=3),
        ),
    ]
