# Generated by Django 2.1.2 on 2018-10-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0026_changes_on_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_company_view', models.BooleanField(default=False)),
                ('supervisor_company_edit', models.BooleanField(default=True)),
                ('supervisor_company_delete', models.BooleanField(default=True)),
                ('supervisor_device_view', models.BooleanField(default=True)),
                ('supervisor_device_edit', models.BooleanField(default=True)),
                ('supervisor_device_delete', models.BooleanField(default=True)),
                ('supervisor_product_view', models.BooleanField(default=True)),
                ('supervisor_product_edit', models.BooleanField(default=True)),
                ('supervisor_product_delete', models.BooleanField(default=True)),
                ('supervisor_users_view', models.BooleanField(default=True)),
                ('supervisor_users_edit', models.BooleanField(default=True)),
                ('supervisor_users_delete', models.BooleanField(default=True)),
                ('supervisor_administration_dashboard', models.BooleanField(default=True)),
                ('engineer_company_view', models.BooleanField(default=True)),
                ('engineer_company_edit', models.BooleanField(default=True)),
                ('engineer_company_delete', models.BooleanField(default=True)),
                ('engineer_device_view', models.BooleanField(default=True)),
                ('engineer_device_edit', models.BooleanField(default=True)),
                ('engineer_device_delete', models.BooleanField(default=True)),
                ('engineer_product_view', models.BooleanField(default=True)),
                ('engineer_product_edit', models.BooleanField(default=True)),
                ('engineer_product_delete', models.BooleanField(default=True)),
                ('engineer_users_view', models.BooleanField(default=False)),
                ('engineer_users_edit', models.BooleanField(default=False)),
                ('engineer_users_delete', models.BooleanField(default=False)),
                ('engineer_administration_dashboard', models.BooleanField(default=False)),
                ('operator_company_view', models.BooleanField(default=False)),
                ('operator_company_edit', models.BooleanField(default=False)),
                ('operator_company_delete', models.BooleanField(default=False)),
                ('operator_device_view', models.BooleanField(default=False)),
                ('operator_device_edit', models.BooleanField(default=False)),
                ('operator_device_delete', models.BooleanField(default=False)),
                ('operator_product_view', models.BooleanField(default=False)),
                ('operator_product_edit', models.BooleanField(default=False)),
                ('operator_product_delete', models.BooleanField(default=False)),
                ('operator_users_view', models.BooleanField(default=False)),
                ('operator_users_edit', models.BooleanField(default=False)),
                ('operator_users_delete', models.BooleanField(default=False)),
                ('operator_administration_dashboard', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
