# Generated by Django 2.1.2 on 2018-12-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0027_changes_on_user_role_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescanRobotMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rescan_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'administration_rescan_robot_machine',
            },
        ),
    ]
