# Generated by Django 2.1.2 on 2018-12-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots_machine', '0001_add_robot_machine'),
        ('administration', '0028_add_robot_machine_rescan'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescanrobotmachine',
            name='robot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots_machine.Robots'),
        ),
    ]
