# Generated by Django 2.1.2 on 2018-12-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0031_extend_recan_robot_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescanrobotmachine',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
