# Generated by Django 2.1.2 on 2019-01-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0032_extend_recan_robot_machine_with_note_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('error', models.BooleanField(default=False)),
                ('warning', models.BooleanField(default=False)),
                ('info', models.BooleanField(default=False)),
                ('robot_activity', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
