# Generated by Django 2.1.2 on 2019-01-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0033_add_robot_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
