# Generated by Django 2.1.2 on 2019-01-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0034_add_robot_notification_add_active_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='email',
            new_name='email1',
        ),
        migrations.AddField(
            model_name='notification',
            name='email2',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='email3',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='email4',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='email5',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
