from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.main_administration, name='main_administration'),
    url(r'^about$', views.about, name='about'),
    url(r'^settings', views.settings, name='about'),
    url(r'^services', views.services, name='services'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^user', views.users, name='user'),
    url(r'^company/list/', views.company_list, name='company_list'),
    url(r'^device/list/', views.device_list, name='company_list'),
    url(r'^product/list/', views.product_list, name='product_list'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    url(r'^notifications', views.notifications_auto_industry, name='notifications_auto_industry'),
    url(r'^monitoring', views.monitoring_auto_industry, name='monitoring_auto_industry'),
    url(r'^user/profile/', views.user_profile),
    url(r'^api/user/$', views.get_user_list),
    url(r'^api/company/$', views.get_company_list),
    url(r'^api/device/', views.get_device_list, name='device_administration'),
    url(r'^api/notification/', views.get_notification_list, name='get_notification_list'),
    url(r'^api/product/', views.get_product_list, name='device_administration'),
    url(r'^api/user/create/', views.create_user),
    url(r'^api/create/notification/', views.create_notification),
    url(r'^api/user/edit/', views.update_user),
    url(r'^api/user/change-password/', views.change_password),
    url(r'^api/user/user-profile/', views.user_profile_form),
    url(r'^api/delete/user/', views.user_delete),
    url(r'^api/service/user/admin_command/', views.user_admin_command),
    url(r'^api/service/user/admin_command_company/', views.user_admin_command_company),
    url(r'^api/service/user/admin_command_product/', views.user_admin_command_product),
    url(r'^api/service/user/admin_command_device/', views.user_admin_device_company),
    url(r'^api/service/user/admin_command_notification/', views.user_admin_notification),
    url(r'^api/delete/company/', views.company_delete),
    url(r'^api/delete/device/', views.device_delete),
    url(r'^api/delete/notification/', views.notification_delete),
    url(r'^api/delete/product/', views.product_delete),
    url(r'^api/edit/user/(?P<id>\d+)/?$', views.edit_user),
    url(r'^api/edit/company/(?P<id>\d+)/?$', views.edit_company),
    url(r'^api/edit/device/(?P<id>\d+)/?$', views.edit_device),
    url(r'^api/edit/product/(?P<id>\d+)/?$', views.edit_product),
    url(r'^api/company/create/', views.create_company, name='company_administration'),
    url(r'^device/create/$', views.create_device, name='device_administration'),
    url(r'^product/create/$', views.create_product, name='product_administration'),
    url(r'^role/templates/', views.user_role, name='user_role'),
    url(r'^rescan/robot/list/$', views.rescan_robot_list, name='get_rescan_robots'),
]
