# Generated by Django 2.1.2 on 2018-12-01 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robots_machine', '0001_add_robot_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='robots',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
