# Generated by Django 2.1.2 on 2018-12-02 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots_machine', '0002_add_created_at_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotWorkingProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_datetime', models.DateTimeField()),
                ('message', models.CharField(default='', max_length=255)),
                ('working_status', models.BooleanField(default=False)),
                ('product_units', models.IntegerField(default=0)),
                ('robot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='robots_machine.Robots')),
            ],
        ),
    ]
