# Generated by Django 2.1.2 on 2018-12-19 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robots_machine', '0004_remove_some_filed_from_robot_working_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotworkingprogress',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='robotworkingprogress',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
