# Generated by Django 2.1.2 on 2018-12-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots_machine', '0005_extend_robot_working_progres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robotworkingprogress',
            old_name='product_units',
            new_name='active_alarms',
        ),
        migrations.RemoveField(
            model_name='robotworkingprogress',
            name='created',
        ),
        migrations.AddField(
            model_name='robotworkingprogress',
            name='excepted_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robotworkingprogress',
            name='good_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robotworkingprogress',
            name='produced_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robotworkingprogress',
            name='rejected_units',
            field=models.IntegerField(default=0),
        ),
    ]
