# Generated by Django 2.1.2 on 2018-12-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots_machine', '0006_add_robot_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotworkingprogress',
            name='down_time',
            field=models.IntegerField(default=0),
        ),
    ]
