# Generated by Django 2.1.2 on 2018-12-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots_machine', '0007_extend_robot_working_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotworkingprogress',
            name='planned_production_time',
            field=models.IntegerField(default=0),
        ),
    ]
