# Generated by Django 2.1.2 on 2018-12-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots_machine', '0008_extend_robot_working_progress_planned_production_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotworkingprogress',
            name='ideal_cycle_time',
            field=models.IntegerField(default=0),
        ),
    ]
