# Generated by Django 2.1.2 on 2019-01-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots_machine', '0010_extend_robot_working_progress_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='ideal_cycle_second',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='robots',
            name='planned_production_hour',
            field=models.IntegerField(default=420),
        ),
    ]
