# Generated by Django 2.1.2 on 2019-01-10 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots_machine', '0011_robot_oee_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotworkingprogress',
            name='ideal_cycle_time',
        ),
        migrations.RemoveField(
            model_name='robotworkingprogress',
            name='planned_production_time',
        ),
    ]
