# Generated by Django 2.1.2 on 2019-01-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots_machine', '0012_remove_some_filed_from_robot_working_progres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robotworkingprogress',
            old_name='down_time',
            new_name='big_errors_type1',
        ),
        migrations.RenameField(
            model_name='robotworkingprogress',
            old_name='total_count',
            new_name='big_errors_type2',
        ),
        migrations.AddField(
            model_name='robotworkingprogress',
            name='errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robotworkingprogress',
            name='errors_max_type1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robotworkingprogress',
            name='errors_max_type2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robotworkingprogress',
            name='good_intensity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robotworkingprogress',
            name='intensity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='robotworkingprogress',
            name='intensity_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robotworkingprogress',
            name='max_errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='robotworkingprogress',
            table='robot_working_progress',
        ),
    ]
