# Generated by Django 2.1.2 on 2019-02-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots_machine', '0013_refactor_robot_working_progres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robots',
            old_name='planned_production_hour',
            new_name='planned_production_min',
        ),
    ]
